theme: jekyll-theme-modernist
title: Lectures on Lean-Agile Product Management
email: humble@berkeley.edu
description: © 2015-2020 Jez Humble, licensed [CC BY-SA](https://creativecommons.org/licenses/by-sa/3.0/us/)